export default Pictures = [
  {
    id: 0,
    name: 'sicili',
    description: "Registro audio pubblico foto indico il luogo dove ho scattato foto Posso rendere il post visibile solo a me",
    imageName: 'cat',
    comments: 'Commment can be anything',
    privacy: 'on',
    audio: 'audio',
    published: new Date().toLocaleDateString(),
  },
  {
    id: 1,
    name: 'palermo',
    description: "Registro audio pubblico foto indico il luogo dove ho scattato foto Posso rendere il post visibile solo a me",
    imageName: 'cat1',
    comments: 'Commment can be anything',
    privacy: 'on',
    audio: 'audio',
    published: new Date().toLocaleDateString(),
  },
  {
    id: 2,
    name: 'milano',
    description: "Registro audio pubblico foto indico il luogo dove ho scattato foto Posso rendere il post visibile solo a me",
    imageName: 'cat2',
    comments: 'Commment can be anything',
    privacy: 'on',
    audio: 'audio',
    published: new Date().toLocaleDateString(),
  },
  {
    id: 3,
    name: 'roma',
    description: "Registro audio pubblico foto indico il luogo dove ho scattato foto Posso rendere il post visibile solo a me",
    imageName: 'cat3',
    comments: 'Commment can be anything',
    privacy: 'on',
    audio: 'audio',
    published: new Date().toLocaleDateString(),
  },
  {
    id: 4,
    name: 'Berlin',
    description: "Registro audio pubblico foto indico il luogo dove ho scattato foto Posso rendere il post visibile solo a me",
    imageName: 'cat4',
    comments: 'Commment can be anything',
    privacy: 'on',
    audio: 'audio',
    published: new Date().toLocaleDateString(),
  },
//   {
//     id: 5,
//     name: 'Nairobi',
//     description: "It's Nairobi",
//     imageName: 'cat5',
//     comments: 'Commment can be anything',
//     privacy: 'on',
//     audio: 'audio',
//     published: new Date(),
//   },
];
